### ISSUE TITLE
SQLITE Database

### ISSUE THREAD

**Issue by ghost** [jamesconrad/Discord-Voice-Normalizer#6]
Got everything working except sqlite. Unable to open database file.
[log.txt](https://github.com/jamesconrad/Discord-Voice-Normalizer/files/4430585/log.txt)

**Comment by devpike** [comment]
[log.txt](https://github.com/jamesconrad/Discord-Voice-Normalizer/files/4430520/log.txt)
Here's my log too

**Comment by devpike** [comment]
Here's my log
[log.txt](https://github.com/jamesconrad/Discord-Voice-Normalizer/files/4430565/log.txt)

**Comment by jamesconrad** [comment]
Just pushed a [fix](https://github.com/jamesconrad/Discord-Voice-Normalizer/commit/b26169fa96572ef2fd9809a2d44c3946839a3c4a), the database file should generate itself if it isn't found.

**Comment by ghost** [comment]
Thanks for the great work. Although it seems it's still not creating the database.
[log.txt](https://github.com/jamesconrad/Discord-Voice-Normalizer/files/4432623/log.txt)

**Comment by ghost** [comment]
I decided to create it manually with the same tables mentioned in sqltablesetup.js, still throws the same error.
[primary.db.txt](https://github.com/jamesconrad/Discord-Voice-Normalizer/files/4432625/primary.db.txt)
Here's the database I created in case you wanted to take a look (I added .txt to the end to upload.)

**Comment by ghost** [comment]
Nevermind. Fixed by using the new config. Thank you, great work.
