### ISSUE TITLE
Bot isn't online

### ISSUE THREAD

**Issue by Caroga** [jamesconrad/Discord-Voice-Normalizer#7]
Hi there!
I just wanted to double check that the bot is currently offline?
The bot has been added by following the URL in your readme. Will the bot be brought back online or should I host my own ?

Kind regards!

**Comment by jamesconrad** [comment]
Sorry been having a few issues with the bot host which have been resolved. The bot is currently online, however if you would like to host your own instance go right ahead and let me know if you encounter any issues.

**Comment by Caroga** [comment]
Thank you for bringing the bot online!
